paw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from paw.constants.base import SCHEDULES, LESSONS, SCHOOL_YEARS, ACCOUNTS
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

handler404 = 'home.views.page_not_found'
handler500 = 'home.views.server_error'

urlpatterns = [
	url(r'^admin', include(admin.site.urls)),
	url(r'^'+SCHEDULES+'/', include('schedules.urls')),
	url(r'^'+LESSONS+'/', include('lessons.urls')),
	url(r'^'+SCHOOL_YEARS+'/', include('schoolyears.urls')),
	url(r'^', include('home.urls')),
]


schoolyears/urls.py
from schoolyears.constants import *
from . import views
from paw.methods import Url

app_name = 'school_years'
urlpatterns = []
url_manager = Url(urlpatterns, views)

url_manager.add_url(EXPRESSION_INDEX, INDEX)
url_manager.add_url(EXPRESSION_INDEX_ACTIVE_ID, INDEX)
url_manager.add_url(EXPRESSION_SCHOOL_YEAR_SAVE, SCHOOL_YEAR_SAVE)
url_manager.add_url(EXPRESSION_SCHOOL_YEAR_SAVE_ACTIVE_ID, SCHOOL_YEAR_SAVE)
url_manager.add_url(EXPRESSION_ADD_SCHOOL, ADD_SCHOOL)
url_manager.add_url(EXPRESSION_UPDATE_SCHOOL, UPDATE_SCHOOL)
url_manager.add_url(EXPRESSION_EDIT_COLOR, EDIT_COLOR)
url_manager.add_url(EXPRESSION_EDIT_SCHEDULE, EDIT_SCHEDULE)
url_manager.add_url(EXPRESSION_SAVE_CALENDAR, SAVE_CALENDAR)
url_manager.add_url(EXPRESSION_ADD_HOME_STATION, ADD_HOME_STATION)
url_manager.add_url(EXPRESSION_ADD_ROUTE, ADD_ROUTE)
url_manager.add_url(EXPRESSION_UPDATE_PATH, UPDATE_PATH)
url_manager.add_url(EXPRESSION_UPDATE_ROUTE, UPDATE_ROUTE)
url_manager.add_url(EXPRESSION_UPDATE_STATION, UPDATE_STATION)
url_manager.add_url(EXPRESSION_ADD_SCHOOL_YEAR_ROUTE, ADD_SCHOOL_YEAR_ROUTE)

schoolyears/models.py
import calendar

from django.utils import timezone

from schedules.models import SchoolPeriodType, SchoolSection
from schoolyears.constants import *
from schoolyears.managers import *


def get_or_none(model_object, latest_column=None, **kwargs):
    try:
        if latest_column is not None:
            return model_object.objects.filter(**kwargs).latest(latest_column)
    except:
        return None

class SchoolYear(models.Model):
    name = models.CharField(max_length=32)
    start_date = models.DateField()
    end_date = models.DateField()
    is_active = models.BooleanField(default=False)
    objects = SchoolYearManager()
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return " | ".join([self.name, str(self.is_active)])

    def update_active_school_year(self):
        current_date = timezone.now().date()
        if self.start_date <= current_date and current_date <= self.end_date:
            SchoolYear.objects.all().update(is_active=False)
            self.is_active = True
        else:
            self.is_active = False
        self.save()

    def update_name(self):
        if self.end_date <= self.start_date:
            return False

        start_year = self.start_date.year
        end_year = self.end_date.year
        self.name = str(start_year)+' ~ '+str(end_year)

        # If the year is the same but the months are different, the name should be: MO1~MO2 YEAR
        if start_year == end_year:
            start_month = self.start_date.month
            end_month = self.end_date.month
            self.name = calendar.month_abbr[start_month]+' ~ '+calendar.month_abbr[end_month]+' '+str(start_year)

        self.save()
        return True

class School(models.Model):
    school_colors = models.CharField(
        max_length=32,
        choices=SCHOOL_COLORS,
        default=GREEN,
    )

    school_type = models.CharField(
        max_length=32,
        choices=SCHOOL_TYPES,
        default=ELEMENTARY_SCHOOL,
    )

    school_year = models.ForeignKey(SchoolYear, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    name_kanji = models.CharField(max_length=256)
    address = models.CharField(max_length=256)
    contact_number = models.CharField(max_length=16)
    website = models.CharField(max_length=256)
    principal = models.CharField(max_length=128)
    vice_principal = models.CharField(max_length=128)
    english_head_teacher = models.CharField(max_length=128)
    created_at = models.DateField(default=timezone.now)
    objects = SchoolManager()
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return " | ".join([str(self.id),
                           self.name,
                           self.school_year.name,
                           self.school_type,
                           self.school_colors])

    def get_hex_color(self):
        school_colors = SchoolManager().get_rearranged_colors()
        return school_colors[self.school_colors]

    def get_readable_school_type(self):
        for school_type in SCHOOL_TYPES:
            if school_type[0] == self.school_type:
                return school_type[1]

    def add_default_school_information(self):
        SchoolPeriodType.objects.add_default_period(self)
        SchoolSection.objects.add_default_school_sections(self)

    def save(self, *args, **kwargs):
        should_add_default_period_entries = False

        if self.id is None: # New entry
            should_add_default_period_entries = True
            same_school_instance = get_or_none(School, 'id', name=self.name, name_kanji=self.name_kanji, school_type=self.school_type)

            # Same school found! Prefill it with the latest existing values
            if same_school_instance is not None:
                school_year = self.school_year
                self = same_school_instance
                self.id = None
                self.school_year = school_year

            # Check list of existing colors in the database with the same school year
            retrieved_colors = [color[0] for color in School.objects.filter(school_year=self.school_year).values_list('school_colors')]
            school_colors = [color[0] for color in SCHOOL_COLORS]
            selected_color = GREEN

            if len(retrieved_colors) > 0:
                for color in school_colors:
                    if color not in retrieved_colors:
                        selected_color = color
                        break

            self.school_colors = selected_color

        super(School, self).save(*args, **kwargs)

        if should_add_default_period_entries:
            self.add_default_school_information()

class Node(models.Model):
    name = models.CharField(max_length=128)
    objects = NodeManager()
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return str(self.name)

class Path(models.Model):
    travel_vehicle_name = models.CharField(max_length=256)
    start_time = models.TimeField()
    end_time = models.TimeField()
    cost = models.IntegerField(default=0)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return " | ".join([str(self.travel_vehicle_name), str(self.start_time),
            str(self.end_time), str(self.cost)])

class RouteInfo(models.Model):
    node = models.ForeignKey(Node, related_name='node')
    next_path = models.ForeignKey(Path, related_name='next_path', blank=True, null=True)
    next_route = models.OneToOneField('self',
        blank=True,
        null=True,
        on_delete=None)
    objects = RouteInfoManager()
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return " || ".join([str(self.node), str(self.next_path)])

class SchoolRoute(models.Model):
    school_year = models.ForeignKey(SchoolYear)
    school = models.ForeignKey(School, null=True)
    source_route_info = models.ForeignKey(RouteInfo, null=True)
    route_name = models.CharField(max_length=128)
    source_name = models.CharField(max_length=128)
    destination_name = models.CharField(max_length=128)
    is_round_trip = models.BooleanField(default=True)
    total_cost = models.IntegerField(default=0)
    is_alt_meeting = models.BooleanField(default=False)
    calculated_total_cost = models.IntegerField(default=0)
    objects = SchoolRouteManager()
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    
    travel_method = models.CharField(
        max_length=16,
        choices=TRAVEL_METHODS,
        default=TRAVEL_METHOD_ID_NA,
    )

    def __str__(self):
        return " ||| ".join([str(self.school_year.id), str(self.school), 
            str(self.source_route_info), str(self.destination_name), 
            str(self.is_round_trip), str(self.total_cost)])

    def update_total_cost(self):
        route_info = RouteInfo.objects.filter(id=self.source_route_info.id)
        self.total_cost = 0
        while route_info.exists():
            route_info = route_info.get()
            if route_info.next_path is not None:
                self.total_cost += route_info.next_path.cost
                route_info = RouteInfo.objects.filter(id=route_info.next_route.id)
            else:
                break
        self.save()

    def update_destination_name(self):
        route_info = RouteInfo.objects.filter(id=self.source_route_info.id)
        node = None
        while route_info.exists():
            route_info = route_info.get()
            node = Node.objects.get(id=route_info.node.id)
            if route_info.next_route is not None:
                route_info = RouteInfo.objects.filter(id=route_info.next_route.id)
            else:
                break
        self.destination_name = node.name
        self.save()

    def compute_calculated_cost(self):
        self.calculated_total_cost = 0
        if self.is_round_trip:
            self.calculated_total_cost = self.total_cost*2
        else:
            self.calculated_total_cost = self.total_cost
        self.save()

    def get_route_info(self):
        school_route_info = []
        route_info = RouteInfo.objects.filter(id=self.source_route_info.id)

        # NOTE: Route info structure. We need the ID for editing.
        # arr[0] = {'node': 'Toyoda Station', 'next_path': 'JR Chuo Line', 'route_id': 12}
        # arr[1] = {'node': 'Hachioji Station', 'next_path': 'JR Yokohama Line', 'route_id': 13}
        # arr[2] = {'node': 'Hashimoto Station', 'next_path': 'Hashimoto 59 Bus', 'route_id': 14}
        # arr[3] = {'node': 'Tana Bus Terminal', 'next_path': null, 'route_id': 15}

        # Enter the loop if there is any route info attached to the school
        while route_info.exists():
            route_info = route_info.get()
            # Retrieve the important route information: node and next path
            node = Node.objects.get(id=route_info.node.id)
            path = None
            current_route_id = route_info.id
            edit_node_form = self.get_node_form(node)

            if route_info.next_path is not None:
                path = Path.objects.get(id=route_info.next_path.id)
            
            edit_path_form = self.get_path_form(path)
            school_route_info.append({'node': node, 
                'path': path, 
                'route_id': current_route_id,
                'path_form': edit_path_form,
                'node_form': edit_node_form})
    
            # Break from the loop if the linked list is over.
            # At this point, the route_info should be complete.
            if route_info.next_route is None:
                break
            else:
                route_info = RouteInfo.objects.filter(id=route_info.next_route.id)

        return school_route_info

    def get_node_form(self, instance):
        from schoolyears.forms import NodeForm
        return NodeForm(instance=instance)

    def get_path_form(self, instance):

schoolyears/forms.py
from django import forms
from django.forms import ModelForm

from schoolyears.constants import *
from schoolyears.models import SchoolYear, School, Path, Node, SchoolRoute


class SchoolYearForm(ModelForm):
    class Meta:
        model = SchoolYear
        fields = ['start_date', 'end_date']
        widgets = {
            'start_date': forms.DateInput(attrs={'class':'datepicker form-control'}),
            'end_date': forms.DateInput(attrs={'class':'datepicker form-control'}),
        }
        labels = { 
            'start_date': NAME_START_DATE,
            'end_date': NAME_END_DATE,
        }

class SchoolForm(ModelForm):
    class Meta:
        model = School
        fields = ['name', 'name_kanji', 'school_type']
        widgets = {
            'name': forms.TextInput(),
            'name_kanji': forms.TextInput(),
            'school_type': forms.Select()
        }
        labels = { 
            'name': NAME_SCHOOL_NAME,
            'name_kanji': NAME_KANJI_NAME,
            'school_type': NAME_SCHOOL_TYPE,
        }
        requireds = {
            'name_kanji': False,
        }

class PathForm(ModelForm):
    class Meta:
        model = Path
        fields = ['travel_vehicle_name', 'start_time', 'end_time', 'cost']
        widgets = {
            'travel_vehicle_name': forms.TextInput(),
            'start_time': forms.TimeInput(attrs={'class':'form-control'}),
            'end_time': forms.TimeInput(attrs={'class':'form-control'}),
            'cost': forms.NumberInput(),
        }
        labels = {
            'travel_vehicle_name': NAME_TRAVEL_VEHICLE,
            'start_time': NAME_START_TIME,
            'end_time': NAME_END_TIME,
            'cost': NAME_COST,
        }

class NodeForm(ModelForm):
    class Meta:
        model = Node
        fields = ['name']
        widgets = {
            'name': forms.TextInput()
        }
        labels = {
            'name': NAME_STATION,
        }

class AddRouteForm(ModelForm):
    class Meta:
        model = SchoolRoute
        fields = ['route_name', 'source_name', 'destination_name', 'travel_method',
            'total_cost', 'is_round_trip', 'is_alt_meeting']
        widgets = {
            'route_name': forms.TextInput(),
            'source_name': forms.TextInput(),
            'destination_name': forms.TextInput(),
            'total_cost': forms.NumberInput(),
            'is_round_trip': forms.CheckboxInput(attrs={'class':'toggle-switch', 
                'data-on-color': 'success', 'data-on-text':'Round Trip', 'data-off-text':'One Way'}),
            'is_alt_meeting': forms.CheckboxInput(attrs={'class':'toggle-switch', 
                'data-on-color': 'success', 'data-on-text':'Yes', 'data-off-text':'No'}),
            'travel_method': forms.Select(),
        }
        labels = {
            'route_name': NAME_ROUTE,
            'source_name': NAME_SOURCE,
            'destination_name': NAME_DESTINATION,
            'travel_method': NAME_TRAVEL_METHOD,
            'is_round_trip': NAME_IS_ROUND_TRIP,
            'is_alt_meeting': NAME_IS_ALT_MEETING,
            'total_cost': NAME_TOTAL_COST,
        }

templates/schoolyears/edit-overall-schedule.html
{% load i18n %}
<div class="row">
	<h2>
		<div class="col-sm-6">
			{% trans "Edit Overall Schedule" %}
		</div>
		<div class="col-sm-6 text-align-right" id="school-year-name">
			{{ active_school_year.name }}
		</div>
	</h2>
</div>
<br/>
<div class="row edit-schedule-row">
	<div class="col-xs-1 hidden-xs">
		<div id="edit-school-color"
			data-default-color="#{{ all_schools.0.school_colors }}"
			data-selected-value="{{ all_schools.0.id }}">
		</div>
	</div>
	<div class="col-xs-3 active-school">{% trans "Active School:" %}</div>
	<div class="col-xs-8 active-school-dropdown">
		<select class="form-control">
			{% get_current_language as LANGUAGE_CODE %}
			{% for school in all_schools %}
				<option value="{{ school.id }}" 
					data-color="#{{ school.school_colors }}">
					{% if LANGUAGE_CODE == 'en' %}
						{{ school.name }}
					{% else %}
						{{ school.name_kanji }}
					{% endif %}
				</option>
			{% endfor %}
			{% for event in special_events %}
				<option value="{{ event.key }}"
					data-color="#{{ event.color }}">
					{{ event.value }}
				</option>
			{% endfor %}
		</select>
	</div>
</div>
<hr/>

templates/schoolyears/edit-schedule-header.html
{% load i18n %}

<a href="/schoolyears/{{ selected_school_year.id }}"> 
	<span class="glyphicon glyphicon-chevron-left"></span>
	{% trans "Back to school year page" %}
</a>

<div class="hidden" 
	id="calendar-data" 
	data-calendar-data="{{ schedule_json }}" 
	data-url="../save_calendar/" 
	data-school-year-id="{{ selected_school_year.id }}">
</div>

<div class="fixed-saving">{% trans "Saving..." %}</div>

templates/schoolyears/edit-schedule-instructions.html
{% load static %}
{% load i18n %}
<div class="row">
	<div class="col-sm-6 page-subheader-left">
		{% trans "Instructions" %}
	</div>
	<div class="col-sm-6 page-subheader-right">
		<button class="btn btn-tertiary toggle-visibility"
				id="toggle-instructions"
				data-target="#instructions"
				data-image-url='{% static "images/edit-calendar-" %}'
				data-has-been-clicked="false">
				{% trans "Show" %}
		</button>
	</div>
</div>
<div class="toggle-visibility-target" id="instructions">
<ul>
<li>{% trans "Click on the Active School dropdown to select your desired school." %}</li>
<li>{% trans "Click on any day within the calendar to toggle its schedule." %}</li>
<li>{% trans "To set a range for a selected school, use SHIFT + Click." %}</li>
<li>{% trans "Click and drag to select a number of days." %}</li>
<li>{% trans "Click the Undo button or CTRL+Z to undo the last action. Note that it is not possible to redo the action once it is undone." %}</li>
<li>{% trans "Click the Save button or CTRL+S to save the calendar to the database." %}</li>
<li>{% trans "Click the Download .ICS button to download the iCAL file. The following shows how to download and import to Google Calendar." %}</li>
</ul>
</div>

templates/schoolyears/edit-schedule-main-calendar.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% bootstrap_icon "repeat" as glyphicon_undo %}
{% bootstrap_icon "download-alt" as glyphicon_download_alt %}
{% bootstrap_icon "floppy-disk" as glyphicon_save %}

<div class="row">
	<div class="col-sm-6 page-subheader-left">
		{% trans "Schedule" %}
	</div>
	<div class="col-sm-6 page-subheader-right">
		<button class="btn btn-secondary" id="btn-download-ics">
			{{ glyphicon_download_alt }} {% trans "Download .ICS" %}</button>
		<button class="btn btn-secondary" id="btn-undo">
			{{ glyphicon_undo }} {% trans "Undo" %}</button>
		<button class="btn btn-primary" id="btn-save">
			{{ glyphicon_save }} {% trans "Save" %}</button>
	</div>
</div>

<div class="row padding-10 calendar-parent">
	<div class="calendar-overlay">{% trans "Saving..." %}</div>
	<calendar-display 
		data-is-editing="true"
		data-start-year="{{ selected_school_year.start_date.year }}"
		data-start-month="{{ selected_school_year.start_date.month }}" 
		data-start-day="{{ selected_school_year.start_date.day }}" 
		data-start-weekday="{{ selected_school_year.start_date.weekday }}" 
		data-end-year="{{ selected_school_year.end_date.year }}" 
		data-end-month="{{ selected_school_year.end_date.month }}" 
		data-end-day="{{ selected_school_year.end_date.day }}"
		data-end-weekday="{{ selected_school_year.end_date.weekday }}"
		data-calendar-data="{{ schedule_json }}"
		data-id-info-map="{{ info_json }}">
	</calendar-display>
</div>

templates/schoolyears/modals.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% bootstrap_icon "pencil" as glyphicon_pencil %}
{% bootstrap_icon "calendar" as glyphicon_calendar %}
<div class="hidden remove-me">
	<modal-content id="add-route">
		<modal-head>
			{% trans "Add Route" %}
		</modal-head>

		<form class="modal-form" action="{% url 'school_years:add_school_year_route' %}"  method="POST">
		<modal-body>
			<div class="alert alert-info">
				<strong>Note:</strong> To add a route that is for going <strong>to or from schools</strong>, please exit this modal and click the <strong>Route Information</strong> button of your respected school.
			</div>
			<br/>
			{% csrf_token %}
			<input type="hidden" name="school_year_id" value="{{ selected_school_year.id }}"/>
			{% bootstrap_field add_route_form.route_name addon_after=glyphicon_pencil placeholder="To ALT Meeting, April ~ July 2017" %}
			{% bootstrap_field add_route_form.source_name addon_after=glyphicon_pencil placeholder="Hachioji Station" %}
			{% bootstrap_field add_route_form.destination_name addon_after=glyphicon_pencil placeholder="Fuchinobe Station" %}
			{% bootstrap_field add_route_form.travel_method %}
			{% bootstrap_field add_route_form.total_cost addon_before="¥" placeholder="240" %}
			<div class="form-group">
				<label class="control-label" for="id_is_round_trip">
					{% trans "Round trip/One Way" %}
				</label><br/>
				{{ add_route_form.is_round_trip }}
			</div>
			<div class="form-group">
				<label class="control-label" for="id_is_alt_meeting">
					{% trans "Is this new route for going to/from an ALT meeting?" %}
				</label><br/>
				{{ add_route_form.is_alt_meeting }}
			</div>
		</modal-body>

		<modal-footer>
			
		</modal-footer>
		</form>
	</modal-content>
	<modal-content id="route-code-generation">
		<modal-head>
			{% trans "Route Code Generation" %}
		</modal-head>
		<modal-body>
			 <div class="row">
				<div class="col-xs-6 page-subheader-left font-weight-500" id="route-info-summary">
					{% trans "Generated code" %}
				</div>
				<div class="col-xs-6 page-subheader-right font-weight-500">
					<button class="btn btn-primary btn-copy" data-clipboard-target="#route-code-generated-script" data-after-click-text='{% trans "Copied!" %}'>
						{%trans "Copy Code" %}
					</button>
				</div>
			</div>
			<pre id="route-code-generated-script"> 
var all_items = [];

{% for route in school_routes %}
all_items.push({
	'route_name': '{{ route.route_name }}',
	'travel_method': '{{ route.travel_method }}',
	'source_station': '{{ route.source_name }}',
	'destination_station': '{{ route.destination_name }}',
	'is_round_trip': {% if route.is_round_trip %}true{% else %}false{% endif %},
	'total_cost': {{ route.total_cost }}
	});
{% endfor %}

	// Loop through the page, adding appropriate values to the appropriate elements
	var selector_route_name_base = 'input[name=destination_';
	var selector_travel_method_base = 'select[name=methods_';
	var selector_source_station_base = 'input[name=from_';
	var selector_destination_station_base = 'input[name=to_';
	var selector_is_round_trip_base = 'input[name=round-trip_';
	var selector_total_cost_base = 'input[name=fee_';
	for (var index=0; index&lt;all_items.length; index+=1) {
	var selector_index = index+1;
	var selector_route_name = selector_route_name_base+selector_index+']';
	var selector_travel_method = selector_travel_method_base+selector_index+']';
	var selector_source_station = selector_source_station_base+selector_index+']';
	var selector_destination_station = selector_destination_station_base+selector_index+']';
	var selector_is_round_trip = selector_is_round_trip_base+selector_index+']';
	var selector_total_cost = selector_total_cost_base+selector_index+']';

	var value_route_name = all_items[index].route_name;
	var value_travel_method = all_items[index].travel_method;
	var value_source_station = all_items[index].source_station;
	var value_destination_station = all_items[index].destination_station;
	var value_is_round_trip = all_items[index].is_round_trip;
	var value_total_cost = all_items[index].total_cost;

	$(selector_route_name).val(value_route_name);
	$(selector_travel_method).val(value_travel_method);
	$(selector_source_station).val(value_source_station);
	$(selector_destination_station).val(value_destination_station);
	$(selector_is_round_trip).attr('checked', value_is_round_trip);
	$(selector_total_cost).val(value_total_cost);
}
			</pre>
		<div class="font-weight-500 font-size-150">{% trans "Instructions" %}</div>
		<div class="instruction-image-code-generation">
			<img src='{% static "images/route-code-generation-tutorial.gif" %}'/>
		</div>
		<br/>
		<ol>
			<li>{% trans "Click \"copy\" to copy the generated code." %}</li>
			<li>{% trans "Go to <a href='https://sites.google.com/a/interacmail.com/hub/'>The Hub</a> &gt; Monthly Expense Claim &gt; Transport Route Registration" %}</li>
			<li>{% trans "Right click and choose \"Inspect\" (Chrome) or \"Inspect Element\" (Firefox)" %}</li>
			<li>{% trans "Click the Console tab" %}</li>
			<li>{% trans "Paste the generated code that was copied in the console." %}</li>
			<li>{% trans "Hit enter, and your routes should be filled in the fields." %}</li>
		</ol>
		</modal-body>
		<modal-footer>
		</modal-footer>
		</form>
	</modal-content>

	{% if edit_form %}
	<modal-content id="edit-schoolyear">
		<modal-head>
			{% trans "Edit School Year: " %}{{ selected_school_year.name }}
		</modal-head>

		<!-- This thing is failing me for some reason url 'school_years:school_year_save' selected_school_year.id -->
		<form class="modal-form" action="/schoolyears/school_year_save/{{ selected_school_year.id }}" method="POST">
		<modal-body>
			{% csrf_token %}
			{% bootstrap_field edit_form.start_date addon_after=glyphicon_calendar placeholder="2017-04-15" %}
			{% bootstrap_field edit_form.end_date addon_after=glyphicon_calendar placeholder="2017-03-31" %}     
		</modal-body>

		<modal-footer>
		</modal-footer>
		</form>
	</modal-content>
	{% endif %}

	{% if add_school_form %}
	<modal-content id="add-school">
		<modal-head>
			{% trans "Add New School" %}
		</modal-head>

		<form class="modal-form" action="/schoolyears/add_school/{{ selected_school_year.id }}" method="POST">
		<modal-body>
			{% csrf_token %}
			{% bootstrap_field add_school_form.name addon_after=glyphicon_pencil placeholder="Tana Elementary School" %}
			{% bootstrap_field add_school_form.name_kanji addon_after=glyphicon_pencil placeholder="田名小学校" %}
			{% bootstrap_field add_school_form.school_type %}
		</modal-body>

		<modal-footer>
		</modal-footer>
		</form>
	</modal-content>
	{% endif %}

	<modal-content id="edit-color">
		<modal-head>
			{% trans "Edit School Color" %}
		</modal-head>

		<form class="modal-form" action="{% url 'school_years:edit_color' %}"  method="POST">
		<modal-body>
			<div class="vertical-center">
				{% csrf_token %}
				<!-- Display all the colors here -->
				<input type="hidden" name="id" id="color-id" value=""/>
				<input type="hidden" name="value" id="color-value" value=""/>
				{% if school_colors is not None %}
					{% for key, color in school_colors.items %}
						<div class="btn school-color modal-school-color color-form" 
							data-color="{{ color }}"
							data-key="{{ key }}">
							<div class="color-checkmark">
								<span class="glyphicon glyphicon-ok"></span>
							</div>
						</div>
					{% endfor %}
				{% else %}
				   There are no available school colors.
				{% endif %}
			</div>
		</modal-body>

		<modal-footer>
			
		</modal-footer>
		</form>
	</modal-content>

	<modal-content id="add-schoolyear">
		<modal-head>
			{% trans "Add New School Year" %}
		</modal-head>

		<form class="modal-form" action="{% url 'school_years:school_year_save' %}"  method="POST">
		<modal-body>
			{% csrf_token %}
			{% bootstrap_field school_year_form.start_date addon_after=glyphicon_calendar placeholder="2017-04-15" %}
			{% bootstrap_field school_year_form.end_date addon_after=glyphicon_calendar placeholder="2018-03-31" %}
		</modal-body>

		<modal-footer>
		</modal-footer>
		</form>
	</modal-content>

</div>

templates/schoolyears/school-header.html
{% load bootstrap3 %}
{% load i18n %}
{% bootstrap_icon "plus" as glyphicon_plus %}
<div class="row">
	<div class="col-xs-6 page-header-left">{% trans "Schools" %}</div>
	<div class="col-xs-6 page-header-right"><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-school" name="add-school-button">
		{{ glyphicon_plus }} {% trans "Add School" %}
	</button></div>
</div>