lessons/urls.py
from lessons.constants import *
from paw.methods import Url
from . import views

app_name = 'lessons'

urlpatterns = []
url_manager = Url(urlpatterns, views)

url_manager.add_url(EXPRESSION_INDEX, INDEX)
url_manager.add_url(EXPRESSION_COURSES, INDEX)
url_manager.add_url(EXPRESSION_ADD_FILE, ADD_FILE)
url_manager.add_url(EXPRESSION_EDIT_FILE, EDIT_FILE)
url_manager.add_url(EXPRESSION_ADD_TOPIC, ADD_TOPIC)
url_manager.add_url(EXPRESSION_ADD_COURSE, ADD_COURSE)
url_manager.add_url(EXPRESSION_ADD_LESSON, ADD_LESSON)
url_manager.add_url(EXPRESSION_INDEX_COURSE_ID, INDEX)
url_manager.add_url(EXPRESSION_EDIT_TOPIC, EDIT_TOPIC)
url_manager.add_url(EXPRESSION_VIEW_LESSON, VIEW_LESSON)
url_manager.add_url(EXPRESSION_DELETE_FILE, DELETE_FILE)
url_manager.add_url(EXPRESSION_EDIT_LESSON, EDIT_LESSON)
url_manager.add_url(EXPRESSION_EDIT_COURSE, EDIT_COURSE)
url_manager.add_url(EXPRESSION_DELETE_TOPIC, DELETE_TOPIC)
url_manager.add_url(EXPRESSION_LESSON_PLANS, LESSON_PLANS)
url_manager.add_url(EXPRESSION_DOWNLOAD_ALL, DOWNLOAD_ALL)
url_manager.add_url(EXPRESSION_DELETE_LESSON, DELETE_LESSON)
url_manager.add_url(EXPRESSION_DOWNLOAD_FILE, DOWNLOAD_FILE)
url_manager.add_url(EXPRESSION_EDIT_ACTIVITY, EDIT_ACTIVITY)
url_manager.add_url(EXPRESSION_VIEW_ACTIVITY, VIEW_ACTIVITY)
url_manager.add_url(EXPRESSION_ADD_FLASHCARD, ADD_FLASHCARD)
url_manager.add_url(EXPRESSION_EDIT_FLASHCARD, EDIT_FLASHCARD)
url_manager.add_url(EXPRESSION_ADD_LESSON_PLAN, ADD_LESSON_PLAN)
url_manager.add_url(EXPRESSION_DELETE_FLASHCARD, DELETE_FLASHCARD)
url_manager.add_url(EXPRESSION_EDIT_LESSON_PLAN, EDIT_LESSON_PLAN)
url_manager.add_url(EXPRESSION_SEARCH_FLASHCARD, SEARCH_FLASHCARD)
url_manager.add_url(EXPRESSION_ADD_EXISTING_FILE, ADD_EXISTING_FILE)
url_manager.add_url(EXPRESSION_LESSON_PLANS_LESSON_ID, LESSON_PLANS)
url_manager.add_url(EXPRESSION_ADD_BOOK_ACTIVITY, ADD_BOOK_ACTIVITY)
url_manager.add_url(EXPRESSION_FLASHCARD_MANAGER, FLASHCARD_MANAGER)
url_manager.add_url(EXPRESSION_ADD_FREE_ACTIVITY, ADD_FREE_ACTIVITY)
url_manager.add_url(EXPRESSION_PRINT_LESSON_PLAN, PRINT_LESSON_PLAN)
url_manager.add_url(EXPRESSION_DOWNLOAD_FLASHCARD, DOWNLOAD_FLASHCARD)
url_manager.add_url(EXPRESSION_GENERIC_ACTIVITIES, GENERIC_ACTIVITIES)
url_manager.add_url(EXPRESSION_GENERATE_FLASHCARD, GENERATE_FLASHCARD)
url_manager.add_url(EXPRESSION_GENERIC_LESSON_PLANS, GENERIC_LESSON_PLANS)
url_manager.add_url(EXPRESSION_ADD_GENERIC_ACTIVITY, ADD_GENERIC_ACTIVITY)
url_manager.add_url(EXPRESSION_EDIT_GENERIC_ACTIVITY, EDIT_GENERIC_ACTIVITY)
url_manager.add_url(EXPRESSION_ADD_EXISTING_FLASHCARD, ADD_EXISTING_FLASHCARD)
url_manager.add_url(EXPRESSION_ADD_GENERIC_LESSON_PLAN, ADD_GENERIC_LESSON_PLAN)
url_manager.add_url(EXPRESSION_DOWNLOAD_ALL_FLASHCARDS, DOWNLOAD_ALL_FLASHCARDS)
url_manager.add_url(EXPRESSION_GENERATE_TARGET_LANGUAGE, GENERATE_TARGET_LANGUAGE)
url_manager.add_url(EXPRESSION_GENERIC_LESSON_PLANS_TOPIC_ID, GENERIC_LESSON_PLANS)
url_manager.add_url(EXPRESSION_ADD_TARGET_LANGUAGE, ADD_TARGET_LANGUAGE)
url_manager.add_url(EXPRESSION_EDIT_TARGET_LANGUAGE, EDIT_TARGET_LANGUAGE)
url_manager.add_url(EXPRESSION_DELETE_TARGET_LANGUAGE, DELETE_TARGET_LANGUAGE)
url_manager.add_url(EXPRESSION_DOWNLOAD_TARGET_LANGUAGE, DOWNLOAD_TARGET_LANGUAGE)
url_manager.add_url(EXPRESSION_DOWNLOAD_ALL_TARGET_LANGUAGES, DOWNLOAD_ALL_TARGET_LANGUAGES)

paw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from paw.constants.base import SCHEDULES, LESSONS, SCHOOL_YEARS, ACCOUNTS
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

handler404 = 'home.views.page_not_found'
handler500 = 'home.views.server_error'

urlpatterns = [
	url(r'^admin', include(admin.site.urls)),
	url(r'^'+SCHEDULES+'/', include('schedules.urls')),
	url(r'^'+LESSONS+'/', include('lessons.urls')),
	url(r'^'+SCHOOL_YEARS+'/', include('schoolyears.urls')),
	url(r'^', include('home.urls')),
]


lessons/models.py
import os
from django.dispatch import receiver

from lessons.constants import *
from lessons.filefield import ContentTypeRestrictedFileField
from lessons.managers import *
from paw.constants.models import *


class Course(models.Model):
    course_name = models.CharField(max_length=32)
    course_code = models.CharField(max_length=12)
    objects = CourseManager()

    def __str__(self):
        return self.course_name

class Lesson(models.Model):
    course = models.ForeignKey(Course)
    lesson_number = models.SmallIntegerField()
    title = models.CharField(max_length=128)
    objects = LessonManager()

    def __str__(self):
        return '%s, Lesson %s' % (self.course.course_code, self.lesson_number)

class Activity(models.Model):
    # For normal activities from the book
    activity_source_type = models.CharField(
        max_length=32,
        choices=ACTIVITY_SOURCE_TYPES,
        default=BOOK_FREE,
    )
    lesson = models.ForeignKey(Lesson, null=True)

    activity_skill_type = models.CharField(
        max_length=32,
        choices=ACTIVITY_SKILL_TYPES,
        default=VOCABULARY,
    )
    activity_name = models.CharField(max_length=256)
    description = models.TextField()
    materials = models.CharField(max_length=256, default=None)

    # For generic activities
    activity_portion_type = models.CharField(
        max_length=32,
        choices=ACTIVITY_PORTION_TYPES,
        default=None,
        null=True
    )
    objects = ActivityManager()

    def set_readable_skill_type(self):
        for item in ACTIVITY_SKILL_TYPES:
            if self.activity_skill_type == item[0]:
                self.activity_skill_type = item[1]

    def set_readable_portion_type(self):
        for item in ACTIVITY_PORTION_TYPES:
            if self.activity_portion_type == item[0]:
                self.activity_portion_type = item[1]

    def is_generic_activity(self):
        return self.lesson is None

    def get_generic_activity_form(self, instance):
        from lessons.forms import GenericActivityForm
        return GenericActivityForm(instance=instance)

    def get_activity_form(self, instance):
        from lessons.forms import ActivityForm
        return ActivityForm(instance=instance)

    def __init__(self, *args, **kwargs):  
        super(Activity, self).__init__(*args, **kwargs)  
        if self.is_generic_activity():
            self.edit_form = self.get_generic_activity_form(instance=self)
        else:
            self.edit_form = self.get_activity_form(instance=self)

    def __str__(self):
        if self.lesson:
            lesson = self.lesson
            course_code = lesson.course.course_code
            lesson_number = str(lesson.lesson_number)
            return course_code+', Lesson '+lesson_number+', '+self.activity_name
        else:
            return self.activity_name

class ActivityFile(models.Model):
    activity = models.ForeignKey(Activity)
    activity_file = ContentTypeRestrictedFileField(upload_to='static/files/', content_types=['*'], max_upload_size=52428800)
    original_filename = models.CharField(max_length=128)
    notes = models.TextField()
    is_link_to_existing_file = models.BooleanField(default=False)

    def get_file_name(self):
        return os.path.basename(self.activity_file.name)

    def __str__(self):
        return " | ".join([str(self.activity_file),
                           os.path.basename(self.activity_file.name)])

class Topic(models.Model):
    name = models.CharField(max_length=64)
    notes = models.TextField()

    def __str__(self):
        return str(self.name)

class LessonPlan(models.Model):
    lesson = models.ForeignKey(Lesson, null=True)
    hour_number = models.SmallIntegerField(null=True)
    greeting = models.ForeignKey(Activity, related_name='greeting', null=True)
    warmup = models.ForeignKey(Activity, related_name='warmup', null=True)
    presentation = models.ForeignKey(Activity, related_name='presentation', null=True)
    practice = models.ForeignKey(Activity, related_name='practice', null=True)
    production = models.ForeignKey(Activity, related_name='production', null=True)
    cooldown = models.ForeignKey(Activity, related_name='cooldown', null=True)
    assessment = models.ForeignKey(Activity, related_name='assessment', null=True)
    is_premade_lesson_plan = models.BooleanField(default=True)
    topic = models.ForeignKey(Topic, null=True)
    objects = LessonPlanManager()
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __get_info_from_activity(self, activity):
        if activity:
            handouts = []
            flashcards = []
            activity_files = ActivityFile.objects.filter(activity=activity, is_link_to_existing_file=False).order_by('original_filename')
            for file in activity_files:
                handout = {'id': file.id, 'filename': file.original_filename}
                if handout not in handouts:
                    handouts.append(handout)

            if activity.lesson is not None:
                lesson = Lesson.objects.get(pk=activity.lesson.id)
                lesson_flashcards = FlashcardLesson.objects.filter(lesson=lesson)
                for lesson_flashcard in lesson_flashcards:
                    flashcard = {'id': lesson_flashcard.flashcard.id, 'flashcard': lesson_flashcard.flashcard.label}
                    if flashcard not in flashcards:
                        flashcards.append(flashcard)

            return {
                'materials': activity.materials,
                'handouts': handouts,
                'flashcards': flashcards,
                'activity': {
                    'id': activity.id,
                    'activity_name': activity.activity_name
                }
            }
        return None

    def __construct_lesson_plan_info_array(self, portion, materials, activities, handouts, flashcards):
        info = self.__get_info_from_activity(portion)
        if info is not None:
            info_materials = info['materials']
            if info_materials != '' and info_materials not in materials and info != '':
                materials.append(info_materials)

            if info['activity'] not in activities:
                activities.append(info['activity'])

            for handout in info['handouts']:
                if handout not in handouts:
                    handouts.append(handout)

            for flashcard in info['flashcards']:
                if flashcard not in flashcards:
                    flashcards.append(flashcard)

    def get_all_info_from_all_activities(self):
        materials = []
        activities = []
        handouts = []
        flashcards = []

        self.__construct_lesson_plan_info_array(self.greeting, materials, activities, handouts, flashcards)
        self.__construct_lesson_plan_info_array(self.warmup, materials, activities, handouts, flashcards)
        self.__construct_lesson_plan_info_array(self.presentation, materials, activities, handouts, flashcards)
        self.__construct_lesson_plan_info_array(self.practice, materials, activities, handouts, flashcards)
        self.__construct_lesson_plan_info_array(self.production, materials, activities, handouts, flashcards)
        self.__construct_lesson_plan_info_array(self.cooldown, materials, activities, handouts, flashcards)
        self.__construct_lesson_plan_info_array(self.assessment, materials, activities, handouts, flashcards)

        return {'materials': materials, 'activities': activities, 'handouts': handouts, 'flashcards': flashcards}

    def __str__(self):
        if self.lesson is not None:
            return self.lesson.course.course_name+", Lesson "+str(self.lesson.lesson_number)+", Hour "+str(self.hour_number)
        else:
            return "Special lesson plan with primary key: "+str(self.id)

class TargetLanguage(models.Model):
    target_language = models.CharField(max_length=128)
    color = models.CharField(
        max_length=32,
        choices=TARGET_LANGUAGE_TYPES,
        default=TARGET_LANGUAGE_RED)
    notes = models.CharField(max_length=64, null=True)
    lesson = models.ForeignKey(Lesson)
    objects = TargetLanguageManager()

    def get_readable_color(self):
        for color in TARGET_LANGUAGE_TYPES:
            if color[0] == self.color:
                return color[1]

    def get_hex_color(self):
        if self.color == TARGET_LANGUAGE_RED:
            return HEX_COLOR_TARGET_LANGUAGE_RED
        elif self.color == TARGET_LANGUAGE_BLUE:
            return HEX_COLOR_TARGET_LANGUAGE_BLUE
        return HEX_COLOR_BLACK

    def get_target_language_form(self, instance):
        from lessons.forms import TargetLanguageForm
        return TargetLanguageForm(instance=instance)

    def __str__(self):
        return self.target_language+' | '+str(self.lesson)

    def __init__(self, *args, **kwargs):  
        super(TargetLanguage, self).__init__(*args, **kwargs)
        self.edit_target_language_form = self.get_target_language_form(instance=self)

class Flashcard(models.Model):
    orientation = models.CharField(
        max_length=32,
        choices=ORIENTATIONS,
        default=PORTRAIT,
    )
    flashcard_type = models.CharField(
        max_length=32,
        choices=FLASHCARD_TYPES,
        default=PICTURE_LABEL,
    )
    # picture = models.FileField(upload_to='')
    picture = ContentTypeRestrictedFileField(upload_to='media/flashcards/', content_types=['image/png', 'image/jpeg'], max_upload_size=5242880)
    label = models.CharField(max_length=128)
    notes = models.CharField(max_length=64)
    is_bordered = models.BooleanField(default=True)
    objects = FlashcardManager()

    def __init__(self, *args, **kwargs):  

templates/lessons/add-course-modal.html
{% load i18n %}
{% load bootstrap3 %}
<div class="hidden remove-me">
	<modal-content id="add-course">
		<modal-head>
			{% trans "Add Book" %}
		</modal-head>

		<form class="modal-form" action="{% url 'lessons:add_course' %}"  method="POST">
		<modal-body>
			{% csrf_token %}
			{% bootstrap_field add_course_form.course_name addon_after=glyphicon_pencil placeholder="Hi Friends 1" %}
			{% bootstrap_field add_course_form.course_code addon_after=glyphicon_pencil placeholder="HiFr1" %}
		</modal-body>

		<modal-footer>
			
		</modal-footer>
		</form>
	</modal-content>
</div>

templates/lessons/add-topic-modal.html
{% load i18n %}
{% load bootstrap3 %}
<div class="hidden remove-me">
	<modal-content id="add-topic">
		<modal-head>
			{% trans "Add Topic" %}
		</modal-head>

		<form class="modal-form" action="{% url 'lessons:add_topic' %}"  method="POST">
		<modal-body>
			{% csrf_token %}
			{% bootstrap_field add_topic_form.name addon_after=glyphicon_pencil placeholder="Animals" %}
			{% bootstrap_field add_topic_form.notes addon_after=glyphicon_pencil placeholder="A generic lesson plan about animals." %}
		</modal-body>

		<modal-footer>
			
		</modal-footer>
		</form>
	</modal-content>
</div>

templates/lessons/courses.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Book:" %} {{ course.course_name }}
{% endblock title %}

{% block additional_css %}
<link type="text/css" rel="stylesheet" href="{% static "css/lessons/courses.css" %}" media="screen"/>
{% endblock additional_css %}

{% block additional_js %}
<script src="{% static "js/lessons/courses.js" %}"></script>
{% endblock additional_js %}

{% block content %}
	{% include "lessons/add-course-modal.html" %}
	{% if course %}
		{% include "lessons/course-header.html" %}
		{% include "lessons/lesson-main-header.html" %}
		<table class="table table-hover margin-top-5">
			<tr>
				<th class="col-xs-2">{% trans "Lesson Number" %}</th>
				<th class="col-xs-5">{% trans "Lesson Title" %}</th>
				<th class="col-xs-5 page-subheader-right">{% trans "Actions" %}</th>
			</tr>
		{% if all_lessons %}
			{% for lesson in all_lessons %}
			<tr>
				<td>{% trans "Lesson" %} <span class="lesson-number">{{ lesson.lesson_number }}</span>
					<div class="hidden remove-me">
						<modal-content id="edit-lesson-{{ lesson.id }}">
							<modal-head>
								Edit {% trans "Lesson" %} {{ lesson.lesson_number }}: {{ lesson.title }}
							</modal-head>

							<form class="modal-form" action="/lessons/edit_lesson"  method="POST">
							<modal-body>
								{% csrf_token %}
								<input type="hidden" name="id" value="{{ lesson.id }}"/>
								<input type="hidden" name="lesson_number" value="{{ lesson.lesson_number }}" />
								{% bootstrap_field lesson.form.title addon_after=glyphicon_pencil placeholder="What would you like? (ランチメニューを作ろう)" %}
							</modal-body>

							<modal-footer>
								
							</modal-footer>
							</form>
						</modal-content>
					</div>
				</td>
				<td>
					<span class="editable-label" 
						data-url="/lessons/edit_lesson" 
						data-id="{{ lesson.id }}"
						data-value="{{ lesson.title }}" 
						data-type="textfield">
							{{ lesson.title }}
					</span>
				</td>
				<td class="page-subheader-right">
					<a href="/lessons/view_lesson/{{ course.id }}/{{ lesson.id }}">
						<button class="btn-secondary btn">
							{% bootstrap_icon "edit" %} {% trans "Edit Activities" %}
						</button>
					</a>
				</td>
			</tr>
			{% endfor %}
		{% else %}
			<tr>
				<td colspan="3" class="center-align">
					{% trans 'There are no lessons available. <br/> Would you like to <a class="cursor-pointer" data-toggle="modal" data-target="#add-lesson" id="add-lesson-from-content">add a new lesson?</a>' %}
				</td>
			</tr>
		{% endif %}
		</table>
	{% else %}
		<div class="row">
			<div class="col-sm-12 center-align">
				{% trans 'There are no books available. <br/> Would you like to <a class="cursor-pointer" data-toggle="modal" data-target="#add-course" id="add-course-from-content">add a new book?</a>' %}
			</div>
		</div>
	{% endif %}
	{% include "lessons/course-modals.html"%}
	<br/>
	<br/>
{% endblock content %}

templates/lessons/flashcard-table.html
{% load i18n %}
{% load bootstrap3 %}
{% load static %}
{% bootstrap_icon "download" as glyphicon_download %}
{% bootstrap_icon "info-sign" as glyphicon_info_sign %}
{% bootstrap_icon "pencil" as glyphicon_pencil %}

<table class="table table-hover margin-top-5 flashcard-table">
	<tr>
		<th class="col-xs-2">{% trans "Name" %}</th>
		<th class="col-xs-1 hidden-xs">{% trans "Orientation" %}</th>
		<th class="col-xs-2 hidden-xs">{% trans "Layout" %}</th>
		<th>{% trans "Notes" %}</th>
		<th class="col-xs-5 page-subsubheader-right">{% trans "Actions" %}</th>
	</tr>
	{% for flashcard_lesson in flashcard_lessons %}
	<tr>
		<td>
			{{ flashcard_lesson.flashcard.label }}<br/>
			{% if display_lesson_information %}
				<span class="small text-muted">({{ flashcard_lesson.lesson }})</span>
			{% endif %}
			<div class="hidden remove-me">
				<modal-content id="edit-flashcard-{{ flashcard_lesson.flashcard.id }}">
					<modal-head>
						{% trans "Edit Flashcard" %}
					</modal-head>

					<form class="modal-form" action="{% url 'lessons:edit_flashcard' %}" method="POST">
					<modal-body>
						{% csrf_token %}
						<div class="row">
							<div class="col-xs-12 vertical-center flashcard-image-wrapper" data-image='{% static "media" %}/{{ flashcard_lesson.flashcard.picture }}'>
								No preview image.
							</div>
						</div>
						<input type="hidden" name="flashcard_id" value="{{ flashcard_lesson.flashcard.id }}" />
						{% bootstrap_field flashcard_lesson.flashcard.edit_flashcard_form.label addon_after=glyphicon_pencil placeholder="Baskbetball" %}
						{% bootstrap_field flashcard_lesson.flashcard.edit_flashcard_form.notes addon_after=glyphicon_pencil placeholder="Sports" %}
						{% bootstrap_field flashcard_lesson.flashcard.edit_flashcard_form.flashcard_type %}
						{% bootstrap_field flashcard_lesson.flashcard.edit_flashcard_form.orientation %}
						<div class="form-group">
							<label class="control-label" for="id_is_bordered">
								{% trans "Flashcard Border" %}
							</label><br/>
							{{ flashcard_lesson.flashcard.edit_flashcard_form.is_bordered }}
						</div>
					</modal-body>

					<modal-footer>
						
					</modal-footer>
					</form>
				</modal-content>
			</div>
		</td>
		<td class="hidden-xs">
		{{ flashcard_lesson.flashcard.get_readable_orientation }}
		</td>
		<td class="font-size-090 hidden-xs">{{ flashcard_lesson.flashcard.get_readable_layout }}</td>
		<td>{{ flashcard_lesson.flashcard.notes }}</td>
		<td class="page-subsubheader-right">
			<a href="/lessons/delete_flashcard/{{ flashcard_lesson.lesson.id }}/{{ flashcard_lesson.flashcard.id }}">
				<button type="button" class="btn btn-tertiary delete-flashcard-button">
					{% bootstrap_icon "trash" %} {% trans "Delete" %}
				</button>
			</a>
			<a href="/lessons/download_flashcard/{{ flashcard_lesson.flashcard.id }}">
				<button type="button" class="btn btn-secondary download-flashcard-button">
					{{ glyphicon_download }} {% trans "Download" %}
				</button>
			</a>

			<button type="button" 
				class="btn btn-primary edit-flashcard-button"
				data-toggle="modal"
				data-flashcard-id="{{ flashcard_lesson.flashcard.id }}"
				data-target="#edit-flashcard-{{ flashcard_lesson.flashcard.id }}">
					{% bootstrap_icon "edit" %} {% trans "Edit" %}
			</button>
		</td>	
	</tr>
	{% endfor %}
</table>

templates/lessons/flashcard_manager.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Flashcard Manager" %}
{% endblock title %}

{% block additional_css %}
<link type="text/css" rel="stylesheet" href="{% static "css/lessons/courses.css" %}" media="screen"/>
{% endblock additional_css %}

{% block additional_js %}
<script src="{% static "js/lessons/flashcard-manager.js" %}"></script>
<script src="{% static "js/lessons/courses.js" %}"></script>
<script src="{% static "js/lessons/lesson-flashcards.js" %}"></script>
{% endblock additional_js %}

{% block content %}
	{% bootstrap_icon "search" as glyphicon_search %}
	{% include "lessons/generate_flashcard.html" %}
	{% include "lessons/generate_target_language.html" %}
	<div class="row">
		<div class="col-sm-6 page-header-left">
			{% trans "Flashcard Manager" %}
		</div>
		<div class="col-sm-6 page-header-right">
			<button 
				type="button" 
				class="btn btn-tertiary" 
				data-toggle="modal" 
				name="generate-target-language"
				data-target="#generate-target-language">
					{% bootstrap_icon "export" %} {% trans "Generate Target Language" %}
			</button>
			<button 
				type="button" 
				class="btn btn-secondary" 
				data-toggle="modal" 
				name="generate-flashcard"
				data-target="#generate-flashcard">
					{% bootstrap_icon "export" %} {% trans "Generate Flashcard" %}
			</button>
		</div>
	</div>
	<table class="table table-hover padding-5">
		<tr>
			<th class="col-sm-3">{% trans "Search Term" %}</th>
			<td>
				<input type="text" class="form-control" id="search-term" name="search" placeholder="(e.g.: &quot;Fruits&quot;, &quot;Basketball&quot;)" {% if search_term %}value="{{ search_term }}"{% endif %}>
			</td>
		</tr>
	</table>
	<div class="row">
		<div class="col-sm-3 col-sm-offset-5">
			<a href="#" id="a-search-flashcard">
				<button class="btn btn-primary" id="btn-search-flashcard">
					{{ glyphicon_search }} {% trans "Search" %}
				</button>			
			</a>
		</div>
	</div>

	{% if search_term %}
		<hr/>
		<div class="row">
			<div class="col-xs-12 page-header-left">
				{% trans "Flashcard Search Results" %}: {{ flashcard_lessons.count }} {% trans "Result(s)" %}
			</div>
		</div>
		{% if flashcard_lessons %}
			{% include "lessons/flashcard-table.html" %}
		{% else %}
			<div class="row">
				<div class="col-sm-12 center-align">
					{% trans 'Your flashcard search yielded no results for the following search term:' %} "{{ search_term }}"{% trans "<span class='japanese-no-results'></span>" %}
				</div>
			</div>
		{% endif %}
		<br/>
		<div class="row">
			<div class="col-xs-12 page-header-left">
				{% trans "Target Language Search Results" %}: {{ target_languages.count }} {% trans "Result(s)" %}
			</div>
		</div>
		{% if target_languages %}
			{% include "lessons/target-language-table.html" %}
		{% else %}
			<div class="row">
				<div class="col-sm-12 center-align">
					{% trans 'Your target language search yielded no results for the following search term:' %} "{{ search_term }}"{% trans "<span class='japanese-no-results'></span>" %}
				</div>
			</div>
		{% endif %}
	{% endif %}
{% endblock content %}

templates/lessons/generate_target_language.html
{% load i18n %}
{% load bootstrap3 %}
{% load static %}

<div class="hidden remove-me">
	<modal-content id="generate-target-language">
		<modal-head>
			{% trans "Generate Target Language" %}
		</modal-head>

		<form class="modal-form" action="/lessons/generate_target_language" method="POST" enctype="multipart/form-data">
		<modal-body>
			{% csrf_token %}
			{% bootstrap_field add_target_language_form.target_language addon_after=glyphicon_pencil placeholder="Where do you want to go?" %}
			{% bootstrap_field add_target_language_form.color %}
			{% bootstrap_field add_target_language_form.notes placeholder="Emphasize the accents on 'where' and 'you'" %}
		</modal-body>

		<modal-footer>
			<div class="remove-save-button"></div>
			<button class="btn btn-primary" type="submit">{% trans "Generate" %}</button>
		</modal-footer>
		</form>
	</modal-content>
</div>